### ISSUE TITLE
Code Analysis of `doasedit`

### ISSUE THREAD

**Issue by awebeer256** [AN3223/scripts#3]
Since `doasedit` is security-sensitive, I've really taken a microscope to it before using it, and that has prompted a couple of questions about its code:

1. Why do you export `TMPDIR` instead of just setting it? My understanding is that that accomplishes nothing within this script, and gives it a potentially unwanted side effect.
2. If the file being edited is something like `/etc/profile`, and you had malicious software running on your system, then couldn't that software perform privilege escalation by quickly editing the `$tmp` file after `${EDITOR:-vi} "$tmp"` but before `doas dd if="$tmp" of="$file"`?

**Comment by AN3223** [comment]
Thank you, I highly appreciate any and all scrutiny!

>     1. Why do you export `TMPDIR` instead of just setting it? My understanding is that that accomplishes nothing within this script, and gives it a potentially unwanted side effect.

It's used by mktemp, and it's done this way for compatibility. Although mktemp is widely available, it's not POSIX and its CLI varies from system to system, but TMPDIR is universally respected as far as I can tell. On the other hand, the -p flag (which usually offers the same behavior) is not available on [macOS](https://ss64.com/osx/mktemp.html) or [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=mktemp&sektion=1).

The side effect should not pose an issue, the variable is only ever exposed to the text editor as well as standard system commands, mktemp should be the only one listening for it. The benefit of having it as an export at the top of the script is that it's more clear to the reader where the files are being stored, and it acts as a safety net for people modifying the script since all calls to mktemp will obey TMPDIR. I am open to prefixing calls to mktemp with `TMPDIR=/dev/shm/` however. 

>     2. If the file being edited is something like `/etc/profile`, and you had malicious software running on your system, then couldn't that software perform privilege escalation by quickly editing the `$tmp` file after `${EDITOR:-vi} "$tmp"` but before `doas dd if="$tmp" of="$file"`?

Yes, however that would require the user with doas rights to be compromised, in which case the malicious software could modify PATH from your shell's rc/profile and replace doasedit with whatever executable they want. The correct usage of mktemp ensures other users do not have read/write access to the files created by this script.

doasedit is really a convenience script for sanely using featureful text editors to edit restricted files. If compromised doas-capable users is a concern then this script is definitely not what you want. Instead, either login as root or use doas with nano/vi (or whatever you might trust to run under root).

**Comment by awebeer256** [comment]
Regarding `TMPDIR`, let me be a bit more clear. My understanding is as follows:

- If `TMPDIR` is exported, and if I call `doasedit` from a terminal, then `TMPDIR` will still be equal to `/dev/shm` in that terminal after `doasedit` finishes. Some users may not want this.
- If `TMPDIR` is merely set, not exported, then the calls to `mktemp` within `doasedit` will still create files in `/dev/shm`, rather than `/tmp` or whatever (because a subshell inherits the environment of its parent shell). Therefore, exporting doesn't add any functionality to `doasedit`.

Am I mistaken about either of these?


> the malicious software could modify PATH from your shell's rc/profile and replace doasedit with whatever executable they want.

Good point; I didn't think of that. I withdraw this concern.

**Comment by AN3223** [comment]
> If `TMPDIR` is exported, and if I call `doasedit` from a terminal, then `TMPDIR` will still be equal to `/dev/shm` in that terminal after `doasedit` finishes. Some users may not want this.

Exports are limited to the scope of the script. Environment variables are only inherited downwards, so a child process doesn't modify the parent process's environment. You might be thinking of "sourcing" which is equivalent to a shell reading commands from a file instead of spawn a child process.

> If `TMPDIR` is merely set, not exported, then the calls to `mktemp` within `doasedit` will still create files in `/dev/shm`, rather than `/tmp` or whatever (because a subshell inherits the environment of its parent shell). Therefore, exporting doesn't add any functionality to `doasedit`.

It needs to be exported for mktemp to see it since mktemp is not a shell builtin command. Without an export it's just a shell variable, which is private to the shell (prefixing a command with `var=val` also exports, as well as `env var=val command`).

Example:

```
user@desktop $ TMPDIR=/dev/shm
user@desktop $ mktemp
/tmp/tmp.LEbhMc
user@desktop $ export TMPDIR=/dev/shm
user@desktop $ mktemp
/dev/shm/tmp.mjoBNB
```

**Comment by awebeer256** [comment]
> You might be thinking of "sourcing"

Yes, I was!

> Without an export it's just a shell variable, which is private to the shell

Oh, so something being an "environment variable" isn't just a description of how it's used; that's an actual concept in the shell with different behaviour than normal (shell) variables? Environment variables are inherited by child processes while shell variables aren't. Shell variables can be read by builtins because calling a builtin doesn't create a child process, but instead triggers some code in the already-running shell that owns the variable. Have I got all that right?

**Comment by AN3223** [comment]
> Oh, so something being an "environment variable" isn't just a description of how it's used; that's an actual concept in the shell with different behaviour than normal (shell) variables? Environment variables are inherited by child processes while shell variables aren't. Shell variables can be read by builtins because calling a builtin doesn't create a child process, but instead triggers some code in the already-running shell that owns the variable. Have I got all that right?

Yeah, pretty much! Just a couple of nitpicks: environment variables are actually part of the operating system (for example, you can see the environment by running `cat /proc/$$/environ`), and only some builtins care about shell variables, such as `read` (it checks the IFS shell variable and sets user specified shell variables). Generally builtins try to use the same input/output model as external commands so their behavior is easier to understand.
